### ISSUE TITLE
Possible to reference Nuxt Tailwind Module for implementation

### ISSUE THREAD

**Issue by rogden** [octoper/vite-tailwind-config-viewer#1]
Hey @octoper! Author of https://github.com/rogden/tailwind-config-viewer here. This isn't an issue :) but wanted to let you know you may be able to achieve what you are looking to do with this plugin by referencing the integration in the Nuxt Tailwind module: https://github.com/nuxt-community/tailwindcss-module/blob/main/src/runtime/config-viewer.ts

Tailwind Config Viewer exposes a createServer function that will create a middleware you can use / proxy through. Hope this helps!

**Comment by octoper** [comment]
Hey @rogden.
Thank you for the tip I'm aware of that but I had some issues when I first tried but when I found time I will around that issue and do it that way!
